name: phpstan

on: [push]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache php modules
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Installing php
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extension-csv: mbstring, xdebug
      - name: Install php modules
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run phpstan.
        run: composer phpstan
